### ISSUE TITLE
Invisible weapons

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#220]
В один прекрасный момент, оружие все стало невидимое, я думал это у меня, но нет,  у другого человека тоже стало. Я подумал, поможет новый раунд, но нет, на целую карту у людей, вот примерно такое оружие в руках. Это m16 =)
![default](https://user-images.githubusercontent.com/7480655/51017786-1b133780-1597-11e9-9d9c-4734c09edcbc.png)

**Comment by dok441** [comment]
Так же замечу у игроков он так же случается.

**Comment by dok441** [comment]
Замечу в дополнение и скины становятся рандомно у кого-то невидимые как и оружие, решение данной проблемы это прописать в консоль record 1 и stop, тогда все будет нормально. Скриншот с невидимым скином предоставлю позже.

**Comment by dok441** [comment]
![1324](https://user-images.githubusercontent.com/7480655/52132422-ef98df80-2660-11e9-80c0-df82132e235c.png)
As we can see, the only gun we see in humans, most importantly it has the usual default skin. Introducing team record 1 is the problem, enter stop, stop the recording
Связанные слова
син.
brigade · squad · outfit · gang · company · party · band · crew · group · staff · squadra · team up · unite · join · collaborate · league · command option
род.
teammate · teamwork · teaming · teamed
Словарь
team [tiːm] сущ  
командаж, бригадаж, сборнаяж, экипажм
(crew, brigade, national team)
группаж, отрядм, коллективм
(group)
упряжкаж
(harness)
сообщить об ошибке

**Comment by Satton2** [comment]
Usually this happens when someone freezes for 2 or more seconds (because of lags or ping). After that someone or something will disappear from the screen of the person. I must say that this sometimes happens in other game modes (such as DarkRP) but I see this much often in TTT2.
This can rarely happen if the person will use some kind of flying camera and will fly very far from himself.
There are several ways to fix this problem from client-side: 1) re-connect 2) «record <filename&gt;» «stop» commands.

**Comment by Alf21** [comment]
I think this is caused by a buggy addon. There are some, e.g. the harpoon. If this still happens in other games, then I can't fix this. I could do a rework, but this should be maintained by the gmod devs. Open an issue in the facepunch repo pls :)
