### ISSUE TITLE
no target hitman

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#221]
У убийцы нету цели, в подготовке я умер, может это повлияло на это.
![default](https://user-images.githubusercontent.com/7480655/51023915-f3799a80-15a9-11e9-9ed6-f28f6de2e422.png)

**Comment by dok441** [comment]
Если наемника воскресили, то у него не будет цели.

**Comment by SchokoShampoo** [comment]
Please test and close

**Comment by dok441** [comment]
Заметил лично, это не исправлено. Я был Hitman, в начале нет цели на 1 картинке видно, потом человек умирает, на 2 картинке видно как цель появилась.
![-](https://user-images.githubusercontent.com/7480655/51787359-9e857900-2192-11e9-8222-15c4882368d9.png)
![default](https://user-images.githubusercontent.com/7480655/51787360-9f1e0f80-2192-11e9-890a-e4e9863d7fe1.png)

**Comment by dok441** [comment]
В дополнение к этому, есть так же баг с оповещение ложным.
![2](https://user-images.githubusercontent.com/7480655/52078966-58774d80-25b6-11e9-9633-f4a29db3db5c.png)
Когда ты уже мертв, тебя оповещает, что ты кого-то убил, но ты мертв...

**Comment by Satton2** [comment]
Today, one person said that when he minimized his game, become a Hitman, and when he return to the game he wasn't able to see his target. It's most likely happens because of lags or ping issues when the round begins.
Maybe creating a «refresh target» option or hidden refresh timer would be the easiest ways to fix it? In my opinion, this option/timer should only refresh the visual part of target system and shouldn't change his actual target.

**Comment by Alf21** [comment]
okay pls test with the new system. I won't add a timer / checker because this will decrease the performance. Package loses should be handled by the engine or gmod, not by the addon developer. To avoid this bug, don't leave this game :D
