### ISSUE TITLE
The transformation into a dove at the vampire

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#249]
Есть проблема или даже недочет с вампиром. Превращение вампира установлено на ходьбу, но чтоб определить труп скрытно, нужно использовать данную клавишу, означает она мешает в итоге играть нормально, поэтому поводу у меня есть предложение на изменение. Я думаю необходимо сделать на F1, бинд кнопки превращения в голубя, то есть, по стандарту поставить на клавишу к примеру "v", она не задействовано никак, а если человек хочет изменить, пусть заходит в F1 и меняет бинд.
Так же предлагаю уведомить вампира, на какую кнопку превращаться(Ты стал вампиром и секунд 15 у тебя по право стороне уведомляют, что на "V" превратится в голубя), очень много людей очень тупые и им необходимо, чтоб все писалось когда у них активная роль, что нажимать и так далее, я это говорю, так-как часто с этим сталкиваюсь.

**Comment by Satton2** [comment]
I agree that this an issue and there must be some way to change a transformation button. Creating a setting in the F1 menu in some tab probably the best solution.
I don't think that we need a notification about the button because it's already states in the Vampire's description. Anyway, I still don't understand why descriptions are in F1 menu and not are pop-ups at the beginning of the round.
