### ISSUE TITLE
Purple icon

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#282]
Иногда в первых раундах особенно не загружаются к некоторых игроков их аватары со стима, пример можем увидеть на данной иллюстрации.
![icon](https://user-images.githubusercontent.com/7480655/53807186-bbbb1d80-3f70-11e9-8bf0-8ecb8d208e65.png)

**Comment by Alf21** [comment]
Hmm seems to be a caching error clientside. This still happens with Bots if they get confirmed the first time, but should work after this... This is asynchronous, the image is downloaded after the player connected, there can still be a lag of downloading if there are many players, a slow internet connection and an instant body confirmation. There is, unfortunately, no workaround (because this is asynchronous). If this image doesn't appear after the second confirm, reopen this issue
