### ISSUE TITLE
Changing equipment to slot 7 and 8

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#293]
![132](https://user-images.githubusercontent.com/7480655/53902403-ebe2e900-4062-11e9-8aaf-053a5796e495.png)
Как я помню, после обновления была экипировка на слоты 7 и 8. Теперь стали 2 предмета на 7, я думаю надо изменить обратно на 7 и 8, так-как очень много людей не понимают, что можно переключать колесиком мышки или же у них стоит быстрая смена оружия и им удобней нажать кнопку.

**Comment by lebroomer** [comment]
I know. That was an active design decision. It was already possible before, that 2 Weapons shared the same slot (depending on the decision of the corresponding weapon author). Now the slot is dependent on the Kind, e.g., Primary, Secondary etc. Hence 2 Special Weapons (Harpoon and Melonlauncher for example), will always share the same slot, but now in a consistent way. Since the requirements are moreover that the amount of weapons per slot are customizable (which includes infinite) and weapons should always refer to the same key for consistent switching, I see no good possibility to always have numeric independent slot numbers, sorry.

**Comment by dok441** [comment]
okey
