### ISSUE TITLE
The jester is a murderer or we need to fix him.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#311]
Так-как шут не должен убивать людей, его задача заключается совсем в другом, я предлагаю убрать возможность толкания ломом людей у него, так-как люди не ждут, что он подойдет и столкнет людей в пропасть.

**Comment by Alf21** [comment]
But in that way, you can test whether he is a jester. Denied

**Comment by dok441** [comment]
А проверить шута, что он не может наносить урон или поднимать магнитной палкой предметы? Вы странно мыслите в этом вопросе.

**Comment by Alf21** [comment]
Avoiding the Jester picking up props can result in a simple testing method. The Jester is made to get killed by the player, not by telling a player to kill him. As a result, players can ask another to push another. If one player isn't able to obey this command, they will be revealed as the jester. Getting killed by a jester is very hard since he can't throw things far away or do any damage. Preventing him from using the crowbar push is no solution. Getting killed by a crowbar push should be punished for stupidity IMO.
If there is no relevant argument, I won't change this. But feel free to make a pull request or ask other people to make a code suggestion :)

**Comment by dok441** [comment]
Okey.
