### ISSUE TITLE
Can't inspect body

### ISSUE THREAD

**Issue by Maqiican** [Alf21/TTT2#340]
Since I've added TTT2 plus some roles its not possible to inspect bodies on my server. When I'm removing the TTT2 objects from my server it's fixed and the inspecting works properly.

**Comment by Alf21** [comment]
Can you send me the error message? If there is no error message (I don't believe), then it's possible that you use an incompatible add-on. Check your server console or send the currently used server collection.

**Comment by Maqiican** [comment]
https://steamcommunity.com/sharedfiles/managecollection/?id=868960024 that's the collection. I don't see any error on the server console on startup and can't look ingame right now.

**Comment by TimGoll** [comment]
You have "TTT Advanced Body Search" installed.
So this problem is on their side, not on ours.

**Comment by Maqiican** [comment]
Na it happend before without that Addon and just installed it in hope it will fix it.

**Comment by TimGoll** [comment]
Please - and I don't want to sound harsh here - make sure that you've read the WS page, checked the server console for addon incompatibilities (looks like [this](https://cdn.discordapp.com/attachments/495532865191411714/557222547683409931/unknown.png)) and make sure there are no errors on the client.

Why am I saying this again? I just checked your list again and you use "TTT sprint" which is explicitly noted as not needed, since sprint is already integrated in TTT2. And I'm sure there are a few more addons which do not work. Please make sure to check all things listed above. I'm quite sure the problem is on your side since TTT2 does work for most people without a problem. Thanks!

**Comment by Maqiican** [comment]
I had TTT Sprint installed because somehow the sprint of your "TTT2" didn't work. I made a new collection and now the body inspect works. Thanks for help !
