### ISSUE TITLE
Bug with clairvoyant

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#41]
When a psychic someone dies from the active roles marked, it ceases to be marked at the TAB and that means he died, this is a bug? Or so intended?

**Comment by Alf21** [comment]
hmmm... Do you mean the clairvoyant is shown to everyone if he dies? If not, try to use other words so that the translator can do a better job. I really like your bug reports, yea, but this translator is horrible and I really need to spend a bunch of time to understand a little bit what you wanna say.

**Comment by dok441** [comment]
Я хочу сказать, что человек из помеченных у ясновидца в таблице игроков умирает и попадает в пропавшие, и для невиновных он пока еще жив, то у ясновидца этот человек тут же прекращает быть помеченным и можно таким образом понять, жив ли человек этот или нет, главное запомнить всех помеченных людей.
P.S Может мне писать так, чтоб вы сами смогли перевести удобным вам переводчиком, если нет, то могу поискать получше переводчик или же просить человека знающего английского переводить, но тогда я буду сообщать об ошибках через длительное время =)

**Comment by Alf21** [comment]
Alright, ty. That's a little bit better, I can better try to understand it ^^ That's definitely a bug. I will fix it directly. In this way, it's okay to write. But I would recommend using a mate to translate it to better explain the situation in complex cases, otherwise it could be impossible to fix some bugs :(

**Comment by Alf21** [comment]
Should be fixed with the newest Clairvoyant version. Ty for the report again :) I will update the Beta add-on in 1h with the newest version

**Comment by dok441** [comment]
It is corrected
