### ISSUE TITLE
Damagelogs additional roles.

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#58]
Can you make "Damagelog.ULX_Autoslay_ForceRole" function in Damagelogs to work properly? It doesn't work properly with new roles. It is very sad to see when some active role dies because of RDM. Currently if this function is enabled, all new roles will disappear or will not work properly.

**Comment by iViscosity** [comment]
I've created a solution to this.

As for 

> Currently if this function is enabled, all new roles will disappear or will not work properly.

This is due to how Tommy implements the ForceRole feature. Basically, he overwrites the SelectRoles() function to prevent people from being selected as Special roles (Traitor/Detective) if they have autoslays. This is done in an Initialize hook, meaning after the Gamemode (TTT2) is done loading. In other words, when SelectRoles() is called, it's calling [Tommy's version](https://github.com/Tommy228/tttdamagelogs/blob/289535fe540b1aaa7fe346b012d3e201f55a2775/lua/damagelogs/server/autoslay.lua#L441) which, obviously, doesn't include custom roles.

My solution requires you removing from [this line](https://github.com/Tommy228/tttdamagelogs/blob/289535fe540b1aaa7fe346b012d3e201f55a2775/lua/damagelogs/server/autoslay.lua#L420) down.

**Comment by dok441** [comment]
![22](https://user-images.githubusercontent.com/7480655/48966774-78f4bb80-eff9-11e8-92d3-2361b2b9ccbf.png)
Не работает.

**Comment by dok441** [comment]
Так же это отключает возрождения шута и неизвестного. Если их убьют.

**Comment by SchokoShampoo** [comment]
Will be fixed with #116
